### ISSUE TITLE
socket2 fails to build

### ISSUE THREAD

**Issue by wayeast** [alexcrichton/socket2-rs#28]
Hi,

I'm not sure if this is an issue with me or with the `socket2` library, but it seemed to appear out of the blue.  That is, there is no clear event between before (when my project was building) and after (when my project was failing to build) to which I can attribute this breakage.  `socket2` is buried deep within my dependency tree -- it is not in my project's Cargo.toml.

#### The error

```
error[E0583]: file not found for module `sys`
  --> /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.8/src/lib.rs:72:5
   |
72 | mod sys;
   |     ^^^
   |
   = help: name the file either sys.rs or sys/mod.rs inside the directory "/home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.8/src"
error: aborting due to previous error
```

#### rustc --version
    rustc 1.30.0-nightly (3bc2ca7e4 2018-09-20)

#### The dependency chain (as near as I can tell)
    actix v0.7.4 -> trust-dns-resolver v0.9.1 -> trust-dns-proto v0.4.0 -> socket2 v0.3.8

If this is not actually a problem with the library, could someone please explain to me how to resolve it on my end?  Thank you.

**Comment by wayeast** [comment]
Sorry, I was being an idiot and confusing `cargo web` with `cargo`. Apologies.

**Comment by murtyjones** [comment]
@wayeast Can you elaborate on how you got this error? Seems to have come up for me out of the blue as well.
