### ISSUE TITLE
Incoming interface would be useful for multicast UDP

### ISSUE THREAD

**Issue by pusateri** [alexcrichton/socket2-rs#29]
In C, you use recvmsg() to get the incoming interface. It's a bit complicated for differences between unix and linux. Not sure about Windows. Sample C code is in this gist:

https://gist.github.com/pusateri/58d4ea943cfbfb7e2b3af955293227fe

recvfrom() won't give you the incoming interface, just the source address.

**Comment by alexcrichton** [comment]
Is there perhaps a missing function to bind for this library? Or could you narrow it down a bit what needs to happen in this library?

**Comment by pusateri** [comment]
recvfrom() doesn't provide the incoming interface for a packet. code that runs on multiple interfaces (like mDNS) needs the incoming interface (usually an index).

**Comment by pusateri** [comment]
This is important for multicast UDP because the destination address is always the multicast IP address and the source address can't be trusted because it's UDP and no 3-way handshake occurs to ensure return reachability. So the incoming interface is necessary to prevent spoofing.

**Comment by alexcrichton** [comment]
@pusateri er right yeah makes sense, but I'm curious what API needs to be added to this library to expose the incoming interface? Or put another way, what would a PR to solve this look like?

**Comment by alexcrichton** [comment]
Hm the implementation here is basically switching to `recvmsg`, right? If that's the case then I think we'd probably want to expose the lowest level API, and leave all the various parsing of the result to calling code (although we could also add conveniences as well)

**Comment by pusateri** [comment]
Sure. I can try documenting a Rust version of recvmsg(). It does a lot more than incoming interface which others will probably appreciate.

**Comment by alexcrichton** [comment]
FWIW I think it'd be fine to basically add that API to this crate at any time, and we could probably just use the same raw pointers as the underlying C APIs and just push the safety to users, making it convenient to at least call the C API

**Comment by pusateri** [comment]
nix-rust/nix#990 includes support for incoming interface index.
