### ISSUE TITLE
Support for passing Path to Socket bind & connect methods

### ISSUE THREAD

**Issue by yoshuawuyts** [alexcrichton/socket2-rs#44]
In [`alexcrichton/mio-uds`](https://github.com/alexcrichton/mio-uds) all socket types are constructed from references to `Path`. This is to match the API of std's unix socket types.

It'd be great if `socket2` would expose extra methods to bind and connect on `Path` types when the `unix` feature is enabled. This would save some unsafe code and boilerplate for consumers implementing unix socket types.

Thanks heaps!

**Comment by sfackler** [comment]
You can construct a `SockAddr` from a `Path`: https://docs.rs/socket2/0.3.11/socket2/struct.SockAddr.html#method.unix

**Comment by yoshuawuyts** [comment]
Oh! Yeah that's pretty much all I need!
