### ISSUE TITLE
SO_NOSIGPIPE not set on ios

### ISSUE THREAD

**Issue by dignifiedquire** [alexcrichton/socket2-rs#83]
I am experiencing trouble with sigpipes using socket2 on ios. The code already sets nosigpipe by default for macos, is there a reason this is not done for ios as well?

**Comment by Thomasdezeeuw** [comment]
No reason I think. I would require changing: https://github.com/alexcrichton/socket2-rs/blob/b3badc7d3d599746a3632666876f1a253476c3c7/src/sys/unix.rs#L264 to `#[cfg(target_vendor = "apple")]`. @dignifiedquire would you like to send a pr?

**Comment by dignifiedquire** [comment]
Done: https://github.com/alexcrichton/socket2-rs/pull/84

I went with `any(target_os = "macos", target_os = "ios")` to match the rest of the cfgs in that file

**Comment by Thomasdezeeuw** [comment]
I think for the long term we should move to `target_vendor` to support tvOS and watchOS (?), but that's fine.
